# These are supported funding model platforms

github: https://github.com/arcesoftware
patreon: https://www.patreon.com/richcoast
paypal: https://www.paypal.me/richcoaststudio 
youtube: https://www.youtube.com/@RichCoast  
